version: "3.3"
services:
  backend:
    container_name: backend-api
    build:
      context: api
      dockerfile: Dockerfile
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 80 ;"
    image: backend-api
    environment:
       POSTGRES_PASSWORD: cdbtest
    ports:
      - "8000:80"
    depends_on:
      - "gis-server"
  db:
    container_name: giscdb
    build:
      context: gis_server
      dockerfile: Dockerfile
    image: giscdbtest
    environment:
       POSTGRES_PASSWORD: cdbtest
    ports:
      - "5432:5432"




